#! /bin/bash

set -e

echo "================================================================================================"
echo "== BUILDING ================================================================================"

ARGS=$@

if [ -z "${BASH_SOURCE[0]}" ] ; then
    LOCAL_DIR=`dirname $0`
else
    LOCAL_DIR=`dirname ${BASH_SOURCE[0]}`
fi

LOCAL_DIR=`realpath ${LOCAL_DIR}`

pushd ${LOCAL_DIR}

if [ -f "./parse-args.sh" ] ; then
    source "./parse-args.sh"
fi

if [ -f "./setup.sh" ] ; then
    source "./setup.sh"
fi

DIRS=`ls`

for entry in ${DIRS} ; do
    if [ -d ${entry} ] ; then
        echo "------------------------------------------------------------------------------------------------"
        echo entering ${entry}
        pushd ${entry}
        if [ ! -f ./build ] ; then
            echo nothing to build
        else
            ./build ${ARGS}
            CODE=$?
            if [ "${CODE}" != "0" ] ; then
                echo failed. exiting with ${CODE}
                exit ${CODE}
            fi
        fi
        popd
    fi
done

popd
