#! /bin/bash

set -e

if [ -f "../parse-args.sh" ] ; then
    source "../parse-args.sh"
fi

if [[ "${START_NORMAL_MONKEY}" != "yes" ]] ; then
    echo skipping
    exit 0
fi

if [[ "${NORMAL_MONKEY_COUNT}" == "0" ]] ; then
    echo skipping
    exit 0
fi

echo starting normal monkeys

DIR=`dirname ${0}`
DIR=`realpath ${DIR}`

NODES=""

if [ "${NODES_COUNT}" != "0" ] ; then
    for i in $(eval echo "{1..${NODES_COUNT}}") ; do
        let PORT=3000+${i}
        NODES="${NODES} http://lww-set-node-${i}:$PORT"
    done
fi

for i in $(eval echo "{1..${NORMAL_MONKEY_COUNT}}") ; do
    pushd ../00-builder/
    echo running with nodes ${NODES} ${EXTERNAL_NODES}
    ./exec -d lww-set-normal-monkey-${i} "${DIR}" "/in" "/in/normal_monkey.clj ${NORMAL_MONKEY_IN_PROCESS_COUNT} ${NODES} ${EXTERNAL_NODES}"
    popd
done

echo all monkeys are up
