#! /bin/bash

set -e

if [ -f "../parse-args.sh" ] ; then
    source "../parse-args.sh"
fi

if [[ "${START_CLIENT_VIEWER_MONKEY}" != "yes" ]] ; then
    echo skipping
    exit 0
fi

if [[ "${CLIENT_VIEWER_MONKEY_COUNT}" == "0" ]] ; then
    echo skipping
    exit 0
fi

echo starting client-viewer monkeys

DIR=`dirname ${0}`
DIR=`realpath ${DIR}`

for i in $(eval echo "{1..${CLIENT_VIEWER_MONKEY_COUNT}}") ; do
    pushd ../00-builder/
    ./exec -d lww-set-client-viewer-monkey-${i} "${DIR}" "/in" "/in/client_viewer_monkey.clj ${NODES_COUNT} ${CLIENT_VIEWER_MONKEY_IN_PROCESS_COUNT}"
    popd
done

echo all monkeys are up
